### ISSUE TITLE
Log out button looks like having offset next to user name

### ISSUE THREAD

**Issue by Ryuno-Ki** [Snyk/www#7]
Loggin in at https://snyk.io/ I noticed, that the "Log out" button looks a bit misplaced next to the username.

Playing around with CSS a bit I found out that giving `.nav-account__logout__button` a `margin-top: -2px;` calms the interface.

But I assume the original reason is in `.nav-account` but I wasn't able to pinpoint it.

Please check logged out before rolling out that fix.

**Comment by maban** [comment]
Hi @Ryuno-Ki! Thank you for sending this and #6 – I've just applied these fixes and they will be rolling into the site soon.
