### ISSUE TITLE
Offer RSS/Atom for blog

### ISSUE THREAD

**Issue by Ryuno-Ki** [Snyk/www#8]
A quick search turned out that there are some plugins which will add RSS support to a Jekyll instance.

This way, people (like me) can subscribe to RSS to get informed on updates.

**Comment by maban** [comment]
Thanks for this! We do have an RSS feed here: https://snyk.io/blog/feed.xml but it's not very obvious on the page. I've added a reference to it in the head so it should flag up now if you're searching for it. That change will roll out shortly.
